iNeed/config/routes.rb
INeed::Application.routes.draw do

  devise_for :suppliers

  devise_for :admins

  devise_for :customers, :controllers => {:registrations => 'registrations'}

  match '/customer/needs/my_needs' => "customer/needs#my_needs", as: :customer_root
  match '/supplier/offers' => "supplier/offers#index", as: :supplier_root
  match '/admin/suppliers/' => "admin/suppliers#index", as: :admin_root
  root :to => 'home#index'
  match '/auth/:provider/callback' => 'authentications#create'
  match 'admins/searching' => 'admins#searching', :as => :searching
  #match 'transactions/insert_code' => 'transactions#insert_code'
  #match 'transactions/insert_code' => 'transactions#insert_code', :as => :insert_code
  #match 'needs/reporting' => 'needs#reporting'
  #match 'needs/reportneed' => 'needs#reportneed'
  #match "/needs/routing" => "needs#reportingComments"
  #match 'needs/:id/comments/reportingcomment' => 'comments#reportingcomment'
  #match 'comments/reportcomment' => 'comments#reportcomment'
  # match "/needs/routing" => "needs#reporting"
  match 'complaints/admin_index' => 'complaints#admin_index', :as => :admin_index
  match 'complaints/admin_index_redirect' => 'complaints#admin_index_redirect' , :as => :admin_index_redirect
  match 'needs/sorting' => 'needs#sorting'
  match 'customers/customer_profile' => 'customers#customer_profile'
  match 'suppliers/supplier_profile' => 'suppliers#supplier_profile'
  match 'users/change_password' => 'users#change_password'
  #match "/needs/routing" => "needs#reporting"
  match "/my_needs/create" => "my_needs#create"


  resources :authentications
  resources :home
  resources :comments do
    collection do
      get :like
      get :dislike
      get :unlike
    end
  end
  resources :complaints
  resources :transactions
  resources :offers
  resources :admins, :only => [:create, :destroy, :index] do
    collection do
      get :hide_marked_comments
      get :hide_marked_needs
      get :reported
    end
  end
  resources :updates
  resources :suppliers
  resources :customers
  resources :needs do
  resources :comments do
    collection do
      get :reportingcomment
      get :report_comment
    end
  end
  resources :message
  resources :categories
    collection do
      get :search
      get :filter
    end
  end
  resources:relatedneeds
 
  resources :autocomplete ,:only => [] do
    collection do
      get :needs
      get :needs_categories
    end
  end

  resources :categories, :only => [:show]

  namespace :admin do
    resources :categories ,:only => [:index, :create] do
      collection do
        delete :destroy
      end
    end
    resources :home, :only => [:index]
    resources :comments ,:only => [] do
      collection do
        get :reported
        get :warn
        get :ban
        get :delete
      end
    end
    resources :complaints, :only => [:index, :show] do
      collection do
        get :delete
        get :mark_as_read
        get :mark_as_unread
      end
    end
    resources :customers, :only => [:edit] do
      collection do
        get :un_ban_marked_customer
      end
    end
    resources :needs , :only => [] do
      collection do
        get :reported
        get :delete
        get :warn
        get :ban
      end
    end
    resources :suppliers, :only => [:index] do
      collection do
        get :approve
        get :reject
        get :ban
        get :warn
        get :un_ban_marked_supplier
      end
    end
    resources :users , :only => [] do
      collection do
        get :mailto_users
        get :banned
        get :un_ban_marked_user
      end
    end
    resources :questions, :only => [:index, :create]
  end

  namespace :customer do
    resources :comments do
      collection do
        post :reportingcomment
        post :report_comment
      end
    end
    resources :needs do
      collection do
        post :reporting
        post :report_need
        get  :my_needs
        post :un_need
        post :iNeed
        get :like
        get :dislike
        get :unlike
        get :clickme
     end
    end
    resources :feedback, :only => [:new, :create]
    resources :offers do
      collection do
        post :subscribe
        post :unsubscribe
      end
    end  
    resources :categories, :only => [:show]
  end


  namespace :supplier do
    resources :offers, :only => [:index] do
    	collection do
    		post :publish
        post :updatedate
        post :updatedelete
        post :activate
    	end
    end
    resources :complaints do
      collection do
        post :updatedelete
      end
    end
    resources :feedbacks, :only => [] do
      collection do
        post :report
        get :view
      end
    end
    resources :transactions, :only => [:index, :create, :new, :destroy, :show] do
      collection do
        get :insert_code
      end
    end
    resources :categories, :only => [:show] do
      collection do
        get :track
        get :untrack
        post :track
        post :untrack
      end
    end
    resources :needs, :only => [:index, :show] do
      collection do
        post :track
        post :untrack
        get  :hot_needs_supplier
        post :notify_view
        post :notify_action
        post :unnotify
      end
    end
  end



  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :registrations
      resources :keys
      resources :customers
      resources :comments
      resources :offers
      resources :needs do
        collection do
        get :getlistrelatedneeds
        post :report_need
        get :search
        post :iNeed
        post :un_need
        end
      end
     end
   end
end

iNeed/app/models/comment.rb
#@Author = Dalia William
#@Author = Nisma El-Nayeb
#@Author = Doha
class Comment
  include Mongoid::Document
  include Mongo::Voteable
  field :reported, type: Boolean #check if that comment is reported or not
  field :reported_comments, type: Hash, default: Hash.new #stores the cutomer ID as its key and the reason why the customer reports a comment as the type opposite to that key.
  field :report_reason, type: String #stores the reason choosed by the customer for reporting a comment
  field :deleted, type: Boolean #check if that comment is deleted or not
  field :content, type: String #this attribute is where the comments is written.

  field :num_reports_on_comment_before_deletion, type: Integer, default: 3
  field :created_on, type: DateTime, default: Time.now #this attribute is to get the current date and time at which the comment was posted.
  belongs_to :user
  belongs_to :need #this indicates that comments has realtion with needs where it belongs to it
  belongs_to :customer #this indicates that comments has realtion with customer where it belongs to it

  #@Author: Doha
  #@Summary: validates that the comment is not empty
  validates_presence_of :content

  #@Author: Nisma El-Nayeb
  #@Summary: makes comments voteable using voteable_mongo gem
  voteable self, :up => +2, :down => -1

  #@author: Dalia William
  #@summary: It deletes the comments and sends an update to each commenter to inform him about the deletion
  #@paramName: ids_to_be_deleted => A list that contains the ids of the comments to be deleted
  def self.delete_reported_comments(ids_to_be_deleted) 
    ids_to_be_deleted.map { |comment_id| Update.create(customer_id: Comment.find(comment_id).customer.id, need_id: Comment.find(comment_id).need.id , type: "delete-c") }
    ids_to_be_deleted.map { |comment_id| Comment.find(comment_id).destroy }
  end

  #@author: Dalia William
  #@summary: It checks whether the number of reports on the comment exceeds num_reports_on_comment_before_deletion.
  #          If the comment exceeds it, it is deleted from our database, an update is sent to the commenter
  #          and the commenter's attribute "number_of_comments_deleted_by_system" is incremented by one. At the end, the 
  #          action checked_num_deleted_comments is called to check whether we should warn/ban the commenter.
  #@paramName: comment_id => The id of the comment to be checked
  def self.check_num_reports_on_comment(comment_id)
    @num_reports = Comment.find(comment_id).reported_comments.length
    if (@num_reports >= Comment.find(comment_id).num_reports_on_comment_before_deletion)
      @customer_id = Comment.find(comment_id).customer.id
      @need_id = Comment.find(comment_id).need.id
      Comment.find(comment_id).destroy
      Update.create(customer_id: @customer_id,need_id: @need_id, type: "delete-c")

      @number_deleted_comments = ((Customer.find(@customer_id)).number_of_comments_deleted_by_system) + 1
      (Customer.find(@customer_id)).update_attribute(:number_of_comments_deleted_by_system, @number_deleted_comments)
      Customer.find(@customer_id).checked_num_deleted_comments
    end
  end

  #@Author: Nisma El-Nayeb
  #@Summary: Gets a specific comment object
  #@paramName: "id" => ID of comment object we want to retrieve
  def self.get_comment(id)
    self.find(id)
  end
  
end

iNeed/app/controllers/admin/comments_controller.rb
#@Author = Dalia William
#@Author = Mohamed Osama
class Admin::CommentsController < AdminController

	#@author: Dalia William
  #@summary: It calls delete_reported_comments in comments controller and passes the comments' ids as parameters.
  #@paramName: params[:comments_ids] => The ids of the comments chosen by the admin in the reported comments view 
	def delete
		@comments = params[:comment_ids]
		Comment.delete_reported_comments(@comments)
		redirect_to reported_admins_path
	end
   #@author = Mohamed Osama
  #@summary = An action which initialzes a list of comments which are reported excluding deleted and hidden comments 
   def reported
     @reported_comments = Comment.where(reported: true).excludes(deleted: true) - Comment.any_in(_id: Admin.find(current_admin.id).hidden_comments) 
    end

  #@author: Dalia William
  #@summary: It first gets the commenters' ids(from the comments ids passed from the view), 
  #          calls warn_customers action (which is in Customer model) than redirects to the reported comments page
  #paramName: params[:reason] => the reason enterred by the admin for warning
  #paramName: params[:comment_ids] => the ids of comments selected by the admin
  def warn
		@reason_for_warning = params[:reason]
    @comments = params[:comment_ids]
    @customers = @comments.map { |comment_id| Comment.find(comment_id).customer.id  }
    Admin.find(current_admin.id).warn_customers(@customers, @reason_for_warning)
    redirect_to reported_admins_path
  end

  #@Author: Tarek Mehrez
  #@Summary: This action gets the checked comments then gets their creators, then ban_marked_customers 
  #are called on current admin
  #@paramName: :comment_ids -> checked comments by the admin 
  #@paramName: :reason -> reason for banning comment creator 
  def ban
    @comments = params[:comment_ids]
    @customers = @comments.map { |comment_id| Comment.find(comment_id).customer.id  }
    Admin.find(current_admin.id).ban_marked_customers(@customers,params[:reason],nil)
    redirect_to reported_admins_path
  end

end

iNeed/app/controllers/api/v1/comments_controller.rb
#@author: Marina Charles
class Api::V1::CommentsController < Api::V1::BaseController
  before_filter :restrict_access, :except => [:show, :index]
  respond_to :json

  def index
    respond_with Comment.all
  end

  def show
    respond_with Comment.find(params[:id])
  end
#@author: Marina Charles
#@summary: in this action i put in xml file the comment to be able to delete it using respond_with

   def destroy
      respond_with Comment.destroy(params[:id])
    end

  def reportcomment
    commentID = params["comment_id"]
    @comment = Comment.find(commentID)
    cust_id = current_customer.id.to_s
    report_type = params["reportcomment"]
    @comment.reportcomment = report_type.to_s
    @comment.update_attributes(reported: true)
    @comment.recordscomment[cust_id]= @comment.reportcomment
    @comment.save
    respond_with @need
  end

  def create
    @comment = @need.comments.build(params[:comment])
    respond_with @comment.save
  end
end

iNeed/app/controllers/comments_controller.rb
#@author: Marina Charles
#@Author: Doha
class CommentsController < ApplicationController


  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  #Author: Doha
  #This action is to create a comment in the need's page, by passing the certain need's ID, and the customer commented ID.
  #@need => gets the need ID, that the comment will be posted on
  #@comment => gets the specific comment on the specified need (by calling it on its ID).
  def create
    @need = Need.find(params[:need_id])
    @comment = @need.comments.build(params[:comment])
    @customer = Customer.find(current_customer.id)
    @comment.update_attributes(:customer => @customer)
    if current_customer != nil
      @banned_customer = Customer.is_banned(current_customer.id)
      @needer = @need.is_needer(current_customer)
    end
     respond_to do |format|
      if @comment.save
        format.js
      elsif blank
        redirect_to :back
      else 
        format.html
        format.js 
      end
    end 
  end

  # PUT /comments/1
  # PUT /comments/1.json
  #this update is not used.
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  #@Author: Nisma El-Nayeb
  #@Summary: action for liking a comment
  #@ParamName: "comment" => the comment that the current_customer wants to like
  #@ParamName: "current_customer" => the current_customer who likes a comment
  #@ParamName: ":up" => indication that the user is voting up as opposed to voting 
  #            down(dislike)
  def like
    comment = Comment.find(params[:comment])
    current_customer.vote(comment, :up)
    @need = comment.need
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
      format.js
    end
  end

  #@Author: Nisma El-Nayeb
  #@Summary: action for disliking a comment
  #@ParamName: "comment" => the comment that the current_customer wants to dislike
  #@ParamName: "current_customer" => the current_customer who dislikes a comment
  #@ParamName: ":down" => indication that the user is voting down as opposed to voting 
  #            up(like)
  def dislike
    comment = Comment.find(params[:comment])
    current_customer.vote(comment, :down)
    @need = comment.need
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
      format.js
    end
  end

  #@Author: Nisma El-Nayeb
  #@Summary: action for undoing liking or disliking a comment
  #@ParamName: "comment" => the comment that the current_customer wants to remove his/her
  #            vote from.
  #@ParamName: "current_customer" => the current_customer who wants to remove his/her
  #            vote.
  def unlike
    comment = Comment.find(params[:comment])
    current_customer.unvote(comment)
    @need = comment.need
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
      format.js
    end
  end
  
#@author: Marina Charles
#@summary: in this action, i get the comment that i want to delete and in customer/needs/_comment_partial.haml exists the button and the notice that makes the customer confirm that he wants to delete his comment(only the one who made the comment can delete it)
#@comment: "id" => get the comment with the following id

  def destroy
    need_id = Comment.find(params[:id]).need.id
    @comment = Comment.find(params[:id])
    @comment.destroy
    @need = Need.find(need_id)


    respond_to do |format|
      format.html { redirect_to :back}
      format.json { head :no_content }
      format.js
    end
  end
 


 

end

iNeed/app/controllers/customer/comments_controller.rb
 #@Author = Doha
 class Customer::CommentsController < ApplicationController



#@Author: "Doha"
#@summary: This action gets the customer ID of a certain comment and saves it as the key of the hash called "recordscomment",
#then it gets the reason why the customer reported this comment and saves it as the value opposite to his ID in the hash,
#and finally it updates the reported boolean to true to indicate that this comment is reported.
#@commentID => gets the comment ID 
#report_type => gets the reason why the customer reported this comment.     
  def report_comment
    @comment = Comment.find(params["comment_id"])
    cust_id = current_customer.id.to_s
    @comment.report_reason = params["report_reason"]
    @comment.update_attributes(reported: true)
    @comment.reported_comments[cust_id]= @comment.report_reason
    @comment.save
    Comment.check_num_reports_on_comment(@comment.id)
    redirect_to :back
  end
end

iNeed/app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

iNeed/app/helpers/comments_helper.rb
module CommentsHelper
end

iNeed/app/views/comments/_comments_partial.html.haml
/@Author= "Marina Hani Charles"
/@Summary= button delete so that only the customer can delete his comments 
/@Author = Nisma El-Nayeb
/@Summary = This partial displays comments made on a certain need. An unbanned customer who is /a needer is the only one who can add a comment, delete his own comments, like, dislike and /undo like/dislike a comment and report other customer's comments.

/ @Author= "Doha"
/ @Controller: CommentsController
/ @Controller: Customer/CommentsController
/ @Summary: I use this partial to post a comment in the need's page.
/ It also contains a form which is a pop-up panel that appears with reporting a comment reasons (which appear as choices for the customer), when the customer press "Report" button
/ @Button: "Report" it is added to a comment that does not belong to the customer commented himself, then it disappears when the customer reports once.


- if @need.comments.size == 0
  %div{:style => "width:350px"}
    .alert.alert-alert
      There are no comments to be displayed yet.
- else

  - for comment in @need.comments.asc('created_on')
    -if !current_customer.nil? and !Customer.is_banned(current_customer.id) and comment.customer.id == current_customer.id
      = button_to "x",comment,:method => :delete, :confirm => 'Are you sure?', :class=>"btn-small  btn-danger",:remote => true,:style => 'float:right;margin-right:20px;'
    %h4
     
      =image_tag comment.customer.photo.url(:normal), :width =>'45px',:height =>'45px'
      = comment.customer.name
      = "says: "
    %p{style: "margin-left:50px;"}
      = comment.content
      %br
    %p= comment.created_on
    - if @need.is_needer(current_customer)
      = link_to image_tag("thumbs_up_icon.jpg", :width => "30px", :height => "30px"), like_comments_path(:comment => comment.id), :remote => true
      = link_to "Like", like_comments_path(:comment => comment.id), :remote => true
      = ":"
      = comment.up_votes_count  
      = "liked this."
      = link_to image_tag("thumbs_down_icon.jpg", :width => "30px", :height => "30px"),dislike_comments_path(:comment => comment.id), :remote => true, :update => { :success => :comment, :failure => "error" }
      = link_to "Dislike", dislike_comments_path(:comment => comment.id), :remote => true, :update => { :success => :comment, :failure => "error" }
      = ":"
      = comment.down_votes_count
      = "disliked this."
      - if current_customer.voted?(comment) == true
        %p= link_to "undo like/dislike", unlike_comments_path(:comment => comment.id), :remote => true, :update => { :success => :comment, :failure => "error" }
    -else
      = image_tag("thumbs_up_icon.jpg", :width => "30px", :height => "30px")
      = comment.up_votes_count
      = "liked this."
      = image_tag("thumbs_down_icon.jpg", :width => "30px", :height => "30px")
      = comment.down_votes_count
      = "disliked this."
    %p{style: "float: right;"}
    -if !current_customer.nil?
      - if !Customer.is_banned(current_customer.id) 
        - if comment.customer.id != current_customer.id
          - if (comment.reported_comments.has_key?(current_customer.id.to_s)) == false && @need.is_needer(current_customer)
            %p
              %a.btn{"data-toggle" => "modal", :href => "#myModal2", :comment_id => comment.id, :onclick => "document.getElementById('comment_id').value = '" + comment.id.to_s+"';"} Report
          
    %hr{style: "clear: both;"}
-if !current_customer.nil?
  - if !Customer.is_banned(current_customer.id) && @need.is_needer(current_customer)
    #newComment{:style => "width:350px;height:130px;background-color:#E8E8E8;"}
      = form_for([@need, Comment.new], :remote => true) do |f|
        %br
        %p{:style => "margin-left:10px;"}
          =image_tag current_customer.photo.url(:normal), :width =>'60px',:height =>'60px'
          = f.text_area :content,:rows => "2", :id => "comment"
        %p{:style => "float:right;margin-right:5px;"}= f.submit "Comment", :class =>"btn-normal btn-primary"
/- if @need.comments.size > 0
#myModal2.modal.hide.fade
  .modal-header
    %button.close{"data-dismiss" => "modal"} ×
    %h3 Report Comment
  .modal-body 
    =form_tag({:controller => 'customer/comments', :action => 'report_comment'}, :need_id => @need.id) do
      =radio_button_tag 'report_reason', 'Abuse Comment', :checked => true 
      Abuse Comment 
      %br 
      =radio_button_tag 'report_reason', 'Spam', :checked => true
      Spam
      %br 
      =radio_button_tag 'report_reason', 'Offensive Comment', :checked => true
      Offensive Comment 
      %br 
      =radio_button_tag 'report_reason', 'Hate Speech', :checked => true  
      Hate Speech 
      %br
      =hidden_field_tag :comment_id, params[:comment_id]
      .modal-footer
        =submit_tag "Submit",:class => 'btn-primary'

iNeed/app/views/comments/_form.html.haml
= form_for @comment do |f|
  -if @comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg
  
  %p
  = f.text_area :content, :cols => "20", :rows => "2"

  .actions
    = f.submit 'Save'

/= link_to 'Back', comments_path

iNeed/app/views/comments/create.js.erb
$("#AllComments").html("<%= escape_javascript(render(:partial => "comments/comments_partial")) %>");
$("#new_comment")[0].reset();

iNeed/app/views/comments/destroy.js.erb
$("#AllComments").html("<%= escape_javascript(render(:partial => "comments/comments_partial")) %>");
$("#new_comment")[0].reset();

iNeed/app/views/comments/dislike.js.erb
$("#AllComments").html("<%= escape_javascript(render(:partial => "comments/comments_partial")) %>");
$("#new_comment")[0].reset();

iNeed/app/views/comments/like.js.erb
$("#AllComments").html("<%= escape_javascript(render(:partial => "comments/comments_partial")) %>");

iNeed/app/views/comments/unlike.js.erb
$("#AllComments").html("<%= escape_javascript(render(:partial => "comments/comments_partial")) %>");
$("#new_comment")[0].reset();