iNeed/config/routes.rb
INeed::Application.routes.draw do

  devise_for :suppliers

  devise_for :admins

  devise_for :customers, :controllers => {:registrations => 'registrations'}

  match '/customer/needs/my_needs' => "customer/needs#my_needs", as: :customer_root
  match '/supplier/offers' => "supplier/offers#index", as: :supplier_root
  match '/admin/suppliers/' => "admin/suppliers#index", as: :admin_root
  root :to => 'home#index'
  match '/auth/:provider/callback' => 'authentications#create'
  match 'admins/searching' => 'admins#searching', :as => :searching
  #match 'transactions/insert_code' => 'transactions#insert_code'
  #match 'transactions/insert_code' => 'transactions#insert_code', :as => :insert_code
  #match 'needs/reporting' => 'needs#reporting'
  #match 'needs/reportneed' => 'needs#reportneed'
  #match "/needs/routing" => "needs#reportingComments"
  #match 'needs/:id/comments/reportingcomment' => 'comments#reportingcomment'
  #match 'comments/reportcomment' => 'comments#reportcomment'
  # match "/needs/routing" => "needs#reporting"
  match 'complaints/admin_index' => 'complaints#admin_index', :as => :admin_index
  match 'complaints/admin_index_redirect' => 'complaints#admin_index_redirect' , :as => :admin_index_redirect
  match 'needs/sorting' => 'needs#sorting'
  match 'customers/customer_profile' => 'customers#customer_profile'
  match 'suppliers/supplier_profile' => 'suppliers#supplier_profile'
  match 'users/change_password' => 'users#change_password'
  #match "/needs/routing" => "needs#reporting"
  match "/my_needs/create" => "my_needs#create"


  resources :authentications
  resources :home
  resources :comments do
    collection do
      get :like
      get :dislike
      get :unlike
    end
  end
  resources :complaints
  resources :transactions
  resources :offers
  resources :admins, :only => [:create, :destroy, :index] do
    collection do
      get :hide_marked_comments
      get :hide_marked_needs
      get :reported
    end
  end
  resources :updates
  resources :suppliers
  resources :customers
  resources :needs do
  resources :comments do
    collection do
      get :reportingcomment
      get :report_comment
    end
  end
  resources :message
  resources :categories
    collection do
      get :search
      get :filter
    end
  end
  resources:relatedneeds
 
  resources :autocomplete ,:only => [] do
    collection do
      get :needs
      get :needs_categories
    end
  end

  resources :categories, :only => [:show]

  namespace :admin do
    resources :categories ,:only => [:index, :create] do
      collection do
        delete :destroy
      end
    end
    resources :home, :only => [:index]
    resources :comments ,:only => [] do
      collection do
        get :reported
        get :warn
        get :ban
        get :delete
      end
    end
    resources :complaints, :only => [:index, :show] do
      collection do
        get :delete
        get :mark_as_read
        get :mark_as_unread
      end
    end
    resources :customers, :only => [:edit] do
      collection do
        get :un_ban_marked_customer
      end
    end
    resources :needs , :only => [] do
      collection do
        get :reported
        get :delete
        get :warn
        get :ban
      end
    end
    resources :suppliers, :only => [:index] do
      collection do
        get :approve
        get :reject
        get :ban
        get :warn
        get :un_ban_marked_supplier
      end
    end
    resources :users , :only => [] do
      collection do
        get :mailto_users
        get :banned
        get :un_ban_marked_user
      end
    end
    resources :questions, :only => [:index, :create]
  end

  namespace :customer do
    resources :comments do
      collection do
        post :reportingcomment
        post :report_comment
      end
    end
    resources :needs do
      collection do
        post :reporting
        post :report_need
        get  :my_needs
        post :un_need
        post :iNeed
        get :like
        get :dislike
        get :unlike
        get :clickme
     end
    end
    resources :feedback, :only => [:new, :create]
    resources :offers do
      collection do
        post :subscribe
        post :unsubscribe
      end
    end  
    resources :categories, :only => [:show]
  end


  namespace :supplier do
    resources :offers, :only => [:index] do
    	collection do
    		post :publish
        post :updatedate
        post :updatedelete
        post :activate
    	end
    end
    resources :complaints do
      collection do
        post :updatedelete
      end
    end
    resources :feedbacks, :only => [] do
      collection do
        post :report
        get :view
      end
    end
    resources :transactions, :only => [:index, :create, :new, :destroy, :show] do
      collection do
        get :insert_code
      end
    end
    resources :categories, :only => [:show] do
      collection do
        get :track
        get :untrack
        post :track
        post :untrack
      end
    end
    resources :needs, :only => [:index, :show] do
      collection do
        post :track
        post :untrack
        get  :hot_needs_supplier
        post :notify_view
        post :notify_action
        post :unnotify
      end
    end
  end



  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :registrations
      resources :keys
      resources :customers
      resources :comments
      resources :offers
      resources :needs do
        collection do
        get :getlistrelatedneeds
        post :report_need
        get :search
        post :iNeed
        post :un_need
        end
      end
     end
   end
end

iNeed/app/controllers/api/v1/offers_controller.rb
class Api::V1::OffersController < Api::V1::BaseController
  respond_to :json
  before_filter :restrict_access
  def index
    respond_with Offer.all
  end

  def show
    respond_with Offer.find(params[:id])
  end

# Author: Karim Tharwat
# Summary: the following method is the Api to the subscribe method
# Author: karim Tharwat
# Summary: this method subscribes the customer to an offer with the quantity he wants to subscribes with
# it does the follwing by checking if there exists a transaction for that customer to that offer, if there is it increases the quantity
# if there isn't it creates a new transaction saves it.
# after finishing one of the previous 2 steps it increases the quantity of the people subscribe to the offer and decreases the number of Needs.
# Parameters: 
#   @quantity: quantity retrieved from view
#   @offer_id: offer id retrieved from view
#   @offer: the offer of the previous id
#   @need_id: the need id retrieved from view
#   @expired: a boolean to get if the offer is expired from the view
#   @transaction: looks of there is a transaction in the database with the customer id and the offer id
#                 if there is it increments its quantity if there is not it creates one with default quantity of 0 
#                 then increments it with the wanted quantity.
# Note: i used the update attribute for the date because i created a method in the model and it kept creating errors
#       this is the API story for the subscribe
  def subscribe
    @quantity = params[:quantity].to_i
    @offer_id = params[:offer_id]
    @offer = Offer.find(@offer_id)
    if @quantity <= 0
      redirect_to :back, :notice => "Quantity must be greater than 0"
    elsif (@quantity + @offer.num_of_subscribed_quantity) > @offer.quantity
      redirect_to :back, :notice => "The total quantity will be exceeding the maximum quantity of the offer"  
    else  
      @need_id = params[:need_id]
      @expired = params[:offer_expired]
      @transaction = Transaction.find_or_create_by(customer_id: current_customer.id, offer_id: @offer_id)
      @transaction.increment_quantity(@quantity)
      if @expired
        @transaction.pending = true
      else
        @transaction.pending = false
      end
      if @transaction.save
          @offer.update_attribute(:last_modified, Date.today)
          @offer.increment_quantity(@quantity)
          redirect_to :back, :notice => "Subscription completed successfully"
      else
          redirect_to :back, :notice => "Please try again"
      end
    end
    respond_with Need.find(@need_id)
  end
  
  #@author: Mohamed Ayman
  #@summary: A method that Customer use to unsubscribe a quantity less than or equal to his quantity of subscription through the API.
  def unsubscribe
    @quantity = params[:quantity].to_i
    @offer_id = params[:offer_id]
    @offer = Offer.find(@offer_id)
    trans = Transaction.where(:customer_id => current_customer.id,:offer_id => @offer_id)
    if trans.empty?
      redirect_to :back, :notice => "Sorry you are not subscribed to this offer"
    elsif @quantity <= 0
      redirect_to :back, :notice => "Quantity must be an integer greater than 0"
    elsif @quantity > trans[0].quantity
      redirect_to :back, :notice => "The unsubscribed quantity must be less than or equal the Subscribed quantity"
    elsif (@offer.num_of_subscribed_quantity - @quantity) < 0
      redirect_to :back, :notice => "The total quantity can't be less than 0"
    elsif @quantity < trans[0].quantity
      @transaction = trans[0]
      @offer.update_attribute(:last_modified, Date.today)
      @offer.update_attribute(:num_of_subscribed_quantity, @offer.num_of_subscribed_quantity - @quantity)
      @transaction.update_attribute(:quantity, @transaction.quantity - @quantity)
      redirect_to :back, :notice => "Unsubscription completed successfully"
    elsif @quantity == @transaction.quantity
      @transaction = trans[0]
      @offer.update_attribute(:last_modified, Date.today)
      @offer.update_attribute(:num_of_subscribed_quantity, @offer.num_of_subscribed_quantity - @quantity)
      @transaction.destroy
      redirect_to :back, :notice => "Unsubscription completed successfully ,you are not in this offer anymore"
    else
      redirect_to :back, :notice => "Please try again"
    end
    respond_with Need.find(@need_id)
  end
end

iNeed/app/controllers/offers_controller.rb
class OffersController < ApplicationController
#@Author: Nourhan Aloush
layout 'supp_master'  
before_filter :authenticate_supplier!
  # GET /offers/1
  # GET /offers/1.json
  #@Author: Nourhan Aloush
  #@Summary: this shows the summary page after submitting the offer
  def show
    begin
      @offer = Offer.find(params[:id])
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @offer }
      end
    rescue
      redirect_to :root, notice: "Nice try, but next time you have to be smarter!"
    end
  end

  # GET /offers/new
  # GET /offers/new.json
  #@Author: Nourhan Aloush
  #@Summary: It creates new offer with the parameters entered
  def new
    begin
      @offer = Offer.new
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @offer }
        format.js
      end
    rescue
      redirect_to :back, notice: "Invalid date !"
    end
  end

  # GET /offers/1/edit
  #This method is called in the summary page
  #@Author: Nourhan Aloush
  #@Summary: it calls by default update
  # => it returns to the form with the info written to edit them
  def edit
    begin
      @offer = Offer.find(params[:id])
    rescue
      redirect_to :back, notice: "Invalid date !"
    end
  end

  # POST /offers
  # POST /offers.json
  #@Author: Nourhan Aloush
  #@Summary: It is called after new is called
  # => It takes the values from params to create new offer
  # => it takes the supplier id from the session and need it from the session, 
  # => need_id is saved in the start of the form
  def create
    begin
      @offer = Offer.new(params[:offer])
      @offer.supplier = Supplier.find(current_supplier.id)
     	@offer.need = Need.find(params[:need_id])

  	respond_to do |format|
        if @offer.save
          if (!@offer.quantity_error)
            flash[:notice] = "The min quantity can't be more than the quantity itself, it has been automatically set to quantity !"
          end
          format.html { redirect_to @offer }
          format.json { render json: @offer, status: :created, location: @offer }
        else
          format.html { render action: "new" , :need_id => params[:need_id]}
          format.json { render json: @offer.errors, status: :unprocessable_entity }
        end
      end
    rescue
      redirect_to :back, notice: "Invalid date !"
    end
    
  end

  # PUT /offers/1
  # PUT /offers/1.json
  #@Author: Nourhan Aloush
  #@Summary: This is called when edit is called by user in summary page
  # => it updates the attributes with new values entered
  def update
    begin
      @offer = Offer.find(params[:id])
  	
      respond_to do |format|
        if @offer.update_attributes(params[:offer])
          if(@offer.published)
          	@offer.update_attribute(:expired, false)
            format.html { redirect_to supplier_offers_path, notice: 'Offer was successfully updated.' }
            format.json { head :no_content }
          else
            format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
            format.json { head :no_content }
          end
        else
          format.html { render action: "edit" }
          format.json { render json: @offer.errors, status: :unprocessable_entity }
        end
      end
    rescue
      redirect_to :back, notice: "Invalid date !"
    end
  end


  def destroy
    begin
      @offer = Offer.find(params[:id])
      @offer.update_attributes(deleted: 'true')
      Update.create(type: 'offer-c-d', offer_id: @offer.id)
      redirect_to supplier_offers_url
    rescue
      redirect_to :root, notice: "Nice try, but next time you have to be smarter!"
    end 
  end

end

iNeed/app/controllers/supplier/offers_controller.rb
#Author = Omar Aly
#Author = Nourhan Aloush
#Author = Mirna ElBendary
class Supplier::OffersController < SupplierController

 layout 'supp_master'

#@Author: Nourhan Aloush
#@Summary: This method is called in the summary page 
# => It changes the boolean published to true to be showed in the need's page and my offers page
  def publish
    begin
      @offer = Offer.find(params[:offer_id])
      @need = Need.find(params[:need_id])
      @offer.update_attributes(published: 'true')
      Update.create(type: 'need-c', need_id: params[:need_id]) 
      @needers = @need.customers
      @needers.each do |needer|
        	UserMailer.subscribed_email(needer, @need).deliver
      end
      redirect_to supplier_offers_path, notice: 'Offer was successfully published!'
    rescue
      redirect_to :root, notice: "Nice try, but next time you have to be smarter!"
    end
  end
  
  
  #Author = Mirna ElBendary
  #summary =  it activates a certain offer on a certain need. so we check, if the minimum 
  #quantity of needs is less than or equal to the total number of subscribed needs. if so we check
  #if it was already activated. if not then the offer is activated and customers get updated.
  
   def activate  
    begin
      @offer = Offer.find(params[:id])
      if(@offer.num_of_subscribed_quantity >= @offer.min_quantity)
        if (@offer.activated == true)
          redirect_to supplier_offers_url, notice: 'Sorry, offer already activated!'
        else 
          @offer.update_attribute(:activated, 'true')
          Update.create(type: 'offer-c-a', offer_id: params[:id]) 
          @transactions = Transaction.where(offer_id: params[:id])
          @transactions.each do |trans|
          	UserMailer.activation_email_customer(trans.customer, @offer).deliver
          end
          redirect_to supplier_offers_url, notice: 'Offer successfully activated!'
        end
      end
    rescue
      redirect_to :root, notice: "Nice try, but next time you have to be smarter!"
    end
   end
#Author = Omar Aly
#Index Page for Offers - Supplier/Offers
#Fetches all of the offers of the current logged in supplier that are not deleted
#Checks if any offers are expired, automatically updates their status
  def index
    begin
      @Offers = Offer.where(supplier_id: current_supplier.id, deleted: false).paginate(:per_page => 10, :page=> params[:page])
      @Offers.each do |offer|
        if offer.expiry_date < Date.today
          offer.update_attributes(expired: true)
        end
      end
    rescue
      redirect_to :root, notice: "Nice try, but next time you have to be smarter!"
    end
  end

#Author = Omar Aly
#Delete Action for Offers
#Changes deleted attribute to true
#Parameters (:offer_id)
  def updatedelete
    begin
      @offer = Offer.find(params[:offer_id])
      @offer.update_attributes(:deleted => true)
      Update.create(type: 'offer-c-d', offer_id: @offer.id)
      @transactions = Transaction.where(offer_id: params[:offer_id])
      @transactions.each do |transaction|
        transaction.update_attributes(deleted: true)
        UserMailer.deleted_offer_email(transaction.customer, @offer).deliver
      end
      redirect_to supplier_offers_url, notice: 'Offer was successfuly deleted!'
    rescue
      redirect_to :root, notice: "Nice try, but next time you have to be smarter!"
    end
  end

#Author = Omar Aly
#Update Date Action, used to extend the expiry date
#Not Actually used throughout the implementation
#Parameters (:offer_id, :date)
  def updatedate
    begin
      if params[:date].nil?
        redirect_to supplier_offers_url
      else
        @offer = Offer.find(params[:offer_id])
        @offer.update_attributes(expired: 'false', expiry_date: params[:date])
        redirect_to supplier_offers_url
      end
    end
    rescue
      redirect_to :root, notice: "Nice try, but next time you have to be smarter!"
    end
end

iNeed/app/helpers/supplier/offers_helper.rb
module Supplier::OffersHelper
end

iNeed/app/views/offers/_form.html.haml
/@Author; Nourhan Aloush
/@Controller: offers
/@action: new
/@Summary: This is the form of the new offer
/ => it takes the inputs of all the attributes and send them to the controller to create an offer
/@Buttons:	1. Proceed => submits the values and calls create
/			=> after the offer is created it redirects to the show page of the offer
/			2. Clear => This clears all the fields to start again

#flash
	%div{:style => "width:400px"}
		- if flash[:notice]
			.alert.alert-success
				=flash[:notice]
		- if flash[:error]
			.alert.alert-error
				=flash[:error]
        
%body
=form_for @offer, :as => :offer,:url => {action: "create", :need_id => params[:need_id]}, :html => { :class => "form-inline", multipart:  true}, :validate => true do |o| 
	-if o.error_messages.length != 0  
		%div{:style => "width:610px"}
			.alert.alert-error
				=o.error_messages
	.control-group
		.controls
			=o.label 'Quantity'
			.control-group-error
			.input
				=o.text_field 'quantity'
				%p.help-block Enter the quantity needed
		.controls
		.controls
			=o.label 'Min quantity'
			.input
				=o.text_field 'min_quantity'
				%p.help-block Enter min quantity accepted to complete the offer
		.controls
		.controls
			=o.label 'Price'
			.input
				=o.text_field 'price'
				%p.help-block Enter the price
		.controls
		.controls
			=o.label 'Expiry Date'
			.input
				=o.text_field 'expiry_date'
				%p.help-block Enter the expiry date
		.controls
		.controls
			=o.label 'Warranty'
			.input
				=o.text_field 'warranty'
				%p.help-block Enter the warranty in months
		.controls
		.controls
			=o.label 'Description'
			.input
				=o.text_area 'description', rows: 7, columns: 40
				%p.help-block Enter a brief description of your offer
		.controls
		
		.form-actions
		%button.btn.btn-primary{type: "submit"} Proceed
		%button.btn.btn-primary{type: "reset"} Clear

iNeed/app/views/offers/_new.html.haml
/@Author: Nourhan Aloush
/@Summary: This renders the form to create new offer
%h1 New offer

= render 'form'

iNeed/app/views/offers/edit.html.haml
/@Author; Nourhan Aloush
/@Controller: offers
/@action: new
/@Summary: This is the form of editing offer
/ => it takes the inputs of all the attributes and send them to the controller to create an offer
/@Buttons:	1. Proceed => submits the values and calls create
/			=> after the offer is edited it either redirects to the show page of the offer if not published
/			=> or myoffers page if it is published 

#flash
	%div{:style => "width:400px"}
		- if flash[:notice]
			.alert.alert-success
				=flash[:notice]
		- if flash[:error]
			.alert.alert-error
				=flash[:error]
				
%body
=form_for @offer, :as => :offer,:url => {action: "update", :need_id => params[:need_id]}, :html => { :class => "form-inline", multipart:  true} do |o| 
	-if(@offer.published)
		.control-group
			.controls
				=o.label 'Expiry Date'
				.input
					=o.text_field 'expiry_date'
					%p.help-block Enter the expiry date
			.controls
		
	-else
		.control-group
			.controls
				=o.label 'Quantity'
				.control-group-error
				.input
					=o.text_field 'quantity'
					%p.help-block Enter the quantity needed
			.controls
			.controls
				=o.label 'Min quantity'
				.input
					=o.text_field 'min_quantity'
					%p.help-block Enter min quantity accepted to complete the offer
			.controls
			.controls
				=o.label 'Price'
				.input
					=o.text_field 'price'
					%p.help-block Enter the price
			.controls
			.controls
				=o.label 'Expiry Date'
				.input
					=o.text_field 'expiry_date'
					%p.help-block Enter the expiry date
			.controls
			.controls
				=o.label 'Warranty'
				.input
					=o.text_field 'warranty'
					%p.help-block Enter the warranty in months
			.controls
			.controls
				=o.label 'Description'
				.input
					=o.text_area 'description', rows: 7, columns: 40
					%p.help-block Enter a brief description of your offer
			.controls
			
	.form-actions
		
	%button.btn.btn-primary{type: "submit"} Submit

iNeed/app/views/offers/new.html.haml
/@Author: Nourhan Aloush
/@Summary: This renders the form to create new offer
%h1 New offer

= render 'form'

iNeed/app/views/offers/new.js.erb
$("#content").html("<%= escape_javascript(render(:partial => "new")) %>");
$("#offer_expiry_date").datepicker({ minDate: 0, dateFormat: "yy-mm-dd"});

iNeed/app/views/offers/show.html.haml
/@Author: Nourhan Aloush
/@Summary:	This view is for the summary page
/			=> It has the info on the new created offer
/			=> The supplier reaches this page after submitting the form of creating new offer
/@Buttons:	1. Publish: publish the offer and make it shown in both my offers and need's page of customer
/			2. Edit: returns back to the new created offer to edit it
/			3. cancel: deleted the offer

%h3.alert-error= flash[:notice]

/This control-group is for using the bootswatch
%body
	%h2= "Here is your offer, please make sure the information provided is correct before submitting:"
	%br
	%h3= 'Quantity: '
	%p
		%b= @offer.quantity.to_s
	%h3= 'Min quantity: '
	%p
		%b= @offer.min_quantity.to_s
	%h3= 'Price: '
	%p
		%b= @offer.price.to_s
	%h3= 'Expiry Date: '
	%p
		%b= @offer.expiry_date.to_s
	%h3= 'Warranty: '
	%p
		%b= @offer.warranty.to_s
	-if(!(@offer.description.blank?))
		%h3= 'Description: '
		%p
			%b= @offer.description
			
	%br
	-if(!@offer.published)
		%b=button_to "Edit" , edit_offer_path(:id => @offer.id), method: :get, :class=>"btn-large  btn-primary", style: "float: left"
		%b=button_to "Delete" , @offer, :confirm => 'Are you sure?', :method => :delete, :class=>"btn-large  btn-primary", style: "float: left"
		%b=button_to "Publish" , publish_supplier_offers_path(:offer_id => @offer.id, :need_id => @offer.need_id), :class=>"btn-large  btn-primary", style: "float: left"
	-else
		%b=button_to "Edit" , edit_offer_path(:id => @offer.id), method: :get, :class=>"btn-large  btn-primary", style: "float: left"
		%b=button_to "Delete" , @offer, :confirm => 'Are you sure?', :method => :delete, :class=>"btn-large  btn-primary", style: "float: left"
		