iNeed/config/routes.rb
INeed::Application.routes.draw do

  devise_for :suppliers

  devise_for :admins

  devise_for :customers, :controllers => {:registrations => 'registrations'}

  match '/customer/needs/my_needs' => "customer/needs#my_needs", as: :customer_root
  match '/supplier/offers' => "supplier/offers#index", as: :supplier_root
  match '/admin/suppliers/' => "admin/suppliers#index", as: :admin_root
  root :to => 'home#index'
  match '/auth/:provider/callback' => 'authentications#create'
  match 'admins/searching' => 'admins#searching', :as => :searching
  #match 'transactions/insert_code' => 'transactions#insert_code'
  #match 'transactions/insert_code' => 'transactions#insert_code', :as => :insert_code
  #match 'needs/reporting' => 'needs#reporting'
  #match 'needs/reportneed' => 'needs#reportneed'
  #match "/needs/routing" => "needs#reportingComments"
  #match 'needs/:id/comments/reportingcomment' => 'comments#reportingcomment'
  #match 'comments/reportcomment' => 'comments#reportcomment'
  # match "/needs/routing" => "needs#reporting"
  match 'complaints/admin_index' => 'complaints#admin_index', :as => :admin_index
  match 'complaints/admin_index_redirect' => 'complaints#admin_index_redirect' , :as => :admin_index_redirect
  match 'needs/sorting' => 'needs#sorting'
  match 'customers/customer_profile' => 'customers#customer_profile'
  match 'suppliers/supplier_profile' => 'suppliers#supplier_profile'
  match 'users/change_password' => 'users#change_password'
  #match "/needs/routing" => "needs#reporting"
  match "/my_needs/create" => "my_needs#create"


  resources :authentications
  resources :home
  resources :comments do
    collection do
      get :like
      get :dislike
      get :unlike
    end
  end
  resources :complaints
  resources :transactions
  resources :offers
  resources :admins, :only => [:create, :destroy, :index] do
    collection do
      get :hide_marked_comments
      get :hide_marked_needs
      get :reported
    end
  end
  resources :updates
  resources :suppliers
  resources :customers
  resources :needs do
  resources :comments do
    collection do
      get :reportingcomment
      get :report_comment
    end
  end
  resources :message
  resources :categories
    collection do
      get :search
      get :filter
    end
  end
  resources:relatedneeds
 
  resources :autocomplete ,:only => [] do
    collection do
      get :needs
      get :needs_categories
    end
  end

  resources :categories, :only => [:show]

  namespace :admin do
    resources :categories ,:only => [:index, :create] do
      collection do
        delete :destroy
      end
    end
    resources :home, :only => [:index]
    resources :comments ,:only => [] do
      collection do
        get :reported
        get :warn
        get :ban
        get :delete
      end
    end
    resources :complaints, :only => [:index, :show] do
      collection do
        get :delete
        get :mark_as_read
        get :mark_as_unread
      end
    end
    resources :customers, :only => [:edit] do
      collection do
        get :un_ban_marked_customer
      end
    end
    resources :needs , :only => [] do
      collection do
        get :reported
        get :delete
        get :warn
        get :ban
      end
    end
    resources :suppliers, :only => [:index] do
      collection do
        get :approve
        get :reject
        get :ban
        get :warn
        get :un_ban_marked_supplier
      end
    end
    resources :users , :only => [] do
      collection do
        get :mailto_users
        get :banned
        get :un_ban_marked_user
      end
    end
    resources :questions, :only => [:index, :create]
  end

  namespace :customer do
    resources :comments do
      collection do
        post :reportingcomment
        post :report_comment
      end
    end
    resources :needs do
      collection do
        post :reporting
        post :report_need
        get  :my_needs
        post :un_need
        post :iNeed
        get :like
        get :dislike
        get :unlike
        get :clickme
     end
    end
    resources :feedback, :only => [:new, :create]
    resources :offers do
      collection do
        post :subscribe
        post :unsubscribe
      end
    end  
    resources :categories, :only => [:show]
  end


  namespace :supplier do
    resources :offers, :only => [:index] do
    	collection do
    		post :publish
        post :updatedate
        post :updatedelete
        post :activate
    	end
    end
    resources :complaints do
      collection do
        post :updatedelete
      end
    end
    resources :feedbacks, :only => [] do
      collection do
        post :report
        get :view
      end
    end
    resources :transactions, :only => [:index, :create, :new, :destroy, :show] do
      collection do
        get :insert_code
      end
    end
    resources :categories, :only => [:show] do
      collection do
        get :track
        get :untrack
        post :track
        post :untrack
      end
    end
    resources :needs, :only => [:index, :show] do
      collection do
        post :track
        post :untrack
        get  :hot_needs_supplier
        post :notify_view
        post :notify_action
        post :unnotify
      end
    end
  end



  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :registrations
      resources :keys
      resources :customers
      resources :comments
      resources :offers
      resources :needs do
        collection do
        get :getlistrelatedneeds
        post :report_need
        get :search
        post :iNeed
        post :un_need
        end
      end
     end
   end
end

iNeed/app/controllers/admin/suppliers_controller.rb
# @Author = Dalia William
# @Author = Nada Nasr
#@Author = Mohamed Osama
class Admin::SuppliersController < AdminsController

  #@author: Dalia William, Nada Nasr
  #@summary: It creates 2 lists, "registered_suppliers" that gets all the registered suppliers(approved and not banned)
  #          and "unregistered_suppliers" that gets all the unregistered suppliers
  def index
    @registered_suppliers = Supplier.registered_not_banned.paginate :order=>'created_at desc', :per_page=>10, :page => params[:registered_suppliers]
    @unregistered_suppliers = Supplier.unregistered.paginate :order=>'created_at desc', :per_page=>10, :page => params[:unregistered_suppliers]
  end

  # @Author: Nada Nasr
  # @Summary: approves the supplier and redirects back to same page
  # @paramName: params[:supplier_id] => the id of the supplier to be approved
  def approve
    Admin.find(current_admin.id).approve_supplier(params[:supplier_id])
    redirect_to :action => 'index', :tab => 'unregistered'
  end

  # @Author: Nada Nasr
  # @Summary: rejects the supplier and redirects back to same page
  # @paramName: params[:supplier_id] => the id of the supplier to be rejected
  def reject
    Admin.find(current_admin.id).reject_supplier(params[:supplier_id])
    redirect_to :action => 'index', :tab => 'unregistered'
  end
  
  #@author: Dalia William
  #@summary: It calls warn_suppliers action (which is in Supplier model) than redirects to the registere suppliers page
  #@paramName: params[:reason] => reason enterred by the admin while warning
  #@paramName: params[:user_ids] => list of supplier ids chosen by the admin
  def warn 
    @reason_for_warning = params[:reason]
    @suppliers = params[:user_ids]
    Admin.find(current_admin.id).warn_suppliers(@suppliers, @reason_for_warning)
    redirect_to :action => 'index', :tab => 'registered'
   end
  #@author = Mohamed Osama
#@summary = takes the suppliers marked by the admin and loop on them unbanning each one of them
  def un_ban_marked_supplier
    #@banned_marked_suppliers = []
    @banned_marked_suppliers = Supplier.find(params[:user_ids])
    #@banned_marked_suppliers.map{|s| s.update_attribute(:banned,nil)}
    for supplier_id in params[:user_ids]
      (Supplier.find(supplier_id)).update_attribute(:banned, nil)
    end
    redirect_to :action => 'index', :tab => 'registered'
  end

  #@Author: Tarek Mehrez
  #@Summary: This action gets the checked suppliers then calls ban_marked_customers on current 
  #@paramName: :user_ids -> checked suppliers by the admin 
  #@paramName: :reason -> reason for banning supplier
  def ban
    Admin.find(current_admin.id).ban_marked_suppliers(params[:user_ids],params[:reason])
    redirect_to :action => 'index'
  end
end

iNeed/app/controllers/api/v1/offers_controller.rb
class Api::V1::OffersController < Api::V1::BaseController
  respond_to :json
  before_filter :restrict_access
  def index
    respond_with Offer.all
  end

  def show
    respond_with Offer.find(params[:id])
  end

# Author: Karim Tharwat
# Summary: the following method is the Api to the subscribe method
# Author: karim Tharwat
# Summary: this method subscribes the customer to an offer with the quantity he wants to subscribes with
# it does the follwing by checking if there exists a transaction for that customer to that offer, if there is it increases the quantity
# if there isn't it creates a new transaction saves it.
# after finishing one of the previous 2 steps it increases the quantity of the people subscribe to the offer and decreases the number of Needs.
# Parameters: 
#   @quantity: quantity retrieved from view
#   @offer_id: offer id retrieved from view
#   @offer: the offer of the previous id
#   @need_id: the need id retrieved from view
#   @expired: a boolean to get if the offer is expired from the view
#   @transaction: looks of there is a transaction in the database with the customer id and the offer id
#                 if there is it increments its quantity if there is not it creates one with default quantity of 0 
#                 then increments it with the wanted quantity.
# Note: i used the update attribute for the date because i created a method in the model and it kept creating errors
#       this is the API story for the subscribe
  def subscribe
    @quantity = params[:quantity].to_i
    @offer_id = params[:offer_id]
    @offer = Offer.find(@offer_id)
    if @quantity <= 0
      redirect_to :back, :notice => "Quantity must be greater than 0"
    elsif (@quantity + @offer.num_of_subscribed_quantity) > @offer.quantity
      redirect_to :back, :notice => "The total quantity will be exceeding the maximum quantity of the offer"  
    else  
      @need_id = params[:need_id]
      @expired = params[:offer_expired]
      @transaction = Transaction.find_or_create_by(customer_id: current_customer.id, offer_id: @offer_id)
      @transaction.increment_quantity(@quantity)
      if @expired
        @transaction.pending = true
      else
        @transaction.pending = false
      end
      if @transaction.save
          @offer.update_attribute(:last_modified, Date.today)
          @offer.increment_quantity(@quantity)
          redirect_to :back, :notice => "Subscription completed successfully"
      else
          redirect_to :back, :notice => "Please try again"
      end
    end
    respond_with Need.find(@need_id)
  end
  
  #@author: Mohamed Ayman
  #@summary: A method that Customer use to unsubscribe a quantity less than or equal to his quantity of subscription through the API.
  def unsubscribe
    @quantity = params[:quantity].to_i
    @offer_id = params[:offer_id]
    @offer = Offer.find(@offer_id)
    trans = Transaction.where(:customer_id => current_customer.id,:offer_id => @offer_id)
    if trans.empty?
      redirect_to :back, :notice => "Sorry you are not subscribed to this offer"
    elsif @quantity <= 0
      redirect_to :back, :notice => "Quantity must be an integer greater than 0"
    elsif @quantity > trans[0].quantity
      redirect_to :back, :notice => "The unsubscribed quantity must be less than or equal the Subscribed quantity"
    elsif (@offer.num_of_subscribed_quantity - @quantity) < 0
      redirect_to :back, :notice => "The total quantity can't be less than 0"
    elsif @quantity < trans[0].quantity
      @transaction = trans[0]
      @offer.update_attribute(:last_modified, Date.today)
      @offer.update_attribute(:num_of_subscribed_quantity, @offer.num_of_subscribed_quantity - @quantity)
      @transaction.update_attribute(:quantity, @transaction.quantity - @quantity)
      redirect_to :back, :notice => "Unsubscription completed successfully"
    elsif @quantity == @transaction.quantity
      @transaction = trans[0]
      @offer.update_attribute(:last_modified, Date.today)
      @offer.update_attribute(:num_of_subscribed_quantity, @offer.num_of_subscribed_quantity - @quantity)
      @transaction.destroy
      redirect_to :back, :notice => "Unsubscription completed successfully ,you are not in this offer anymore"
    else
      redirect_to :back, :notice => "Please try again"
    end
    respond_with Need.find(@need_id)
  end
end

iNeed/app/controllers/offers_controller.rb
class OffersController < ApplicationController
#@Author: Nourhan Aloush
layout 'supp_master'  
before_filter :authenticate_supplier!
  # GET /offers/1
  # GET /offers/1.json
  #@Author: Nourhan Aloush
  #@Summary: this shows the summary page after submitting the offer
  def show
    begin
      @offer = Offer.find(params[:id])
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @offer }
      end
    rescue
      redirect_to :root, notice: "Nice try, but next time you have to be smarter!"
    end
  end

  # GET /offers/new
  # GET /offers/new.json
  #@Author: Nourhan Aloush
  #@Summary: It creates new offer with the parameters entered
  def new
    begin
      @offer = Offer.new
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @offer }
        format.js
      end
    rescue
      redirect_to :back, notice: "Invalid date !"
    end
  end

  # GET /offers/1/edit
  #This method is called in the summary page
  #@Author: Nourhan Aloush
  #@Summary: it calls by default update
  # => it returns to the form with the info written to edit them
  def edit
    begin
      @offer = Offer.find(params[:id])
    rescue
      redirect_to :back, notice: "Invalid date !"
    end
  end

  # POST /offers
  # POST /offers.json
  #@Author: Nourhan Aloush
  #@Summary: It is called after new is called
  # => It takes the values from params to create new offer
  # => it takes the supplier id from the session and need it from the session, 
  # => need_id is saved in the start of the form
  def create
    begin
      @offer = Offer.new(params[:offer])
      @offer.supplier = Supplier.find(current_supplier.id)
     	@offer.need = Need.find(params[:need_id])

  	respond_to do |format|
        if @offer.save
          if (!@offer.quantity_error)
            flash[:notice] = "The min quantity can't be more than the quantity itself, it has been automatically set to quantity !"
          end
          format.html { redirect_to @offer }
          format.json { render json: @offer, status: :created, location: @offer }
        else
          format.html { render action: "new" , :need_id => params[:need_id]}
          format.json { render json: @offer.errors, status: :unprocessable_entity }
        end
      end
    rescue
      redirect_to :back, notice: "Invalid date !"
    end
    
  end

  # PUT /offers/1
  # PUT /offers/1.json
  #@Author: Nourhan Aloush
  #@Summary: This is called when edit is called by user in summary page
  # => it updates the attributes with new values entered
  def update
    begin
      @offer = Offer.find(params[:id])
  	
      respond_to do |format|
        if @offer.update_attributes(params[:offer])
          if(@offer.published)
          	@offer.update_attribute(:expired, false)
            format.html { redirect_to supplier_offers_path, notice: 'Offer was successfully updated.' }
            format.json { head :no_content }
          else
            format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
            format.json { head :no_content }
          end
        else
          format.html { render action: "edit" }
          format.json { render json: @offer.errors, status: :unprocessable_entity }
        end
      end
    rescue
      redirect_to :back, notice: "Invalid date !"
    end
  end


  def destroy
    begin
      @offer = Offer.find(params[:id])
      @offer.update_attributes(deleted: 'true')
      Update.create(type: 'offer-c-d', offer_id: @offer.id)
      redirect_to supplier_offers_url
    rescue
      redirect_to :root, notice: "Nice try, but next time you have to be smarter!"
    end 
  end

end

iNeed/app/controllers/supplier_controller.rb
class SupplierController < ApplicationController
before_filter :authenticate_supplier!
end

iNeed/app/helpers/admin/suppliers_helper.rb
module Admin::SuppliersHelper
end

iNeed/app/helpers/supplier/needs_helper.rb
module Supplier::NeedsHelper
end

iNeed/app/helpers/supplier/offers_helper.rb
module Supplier::OffersHelper
end

iNeed/app/helpers/supplier/updates_helper.rb
module Supplier::UpdatesHelper
end

iNeed/app/helpers/supplier_helper.rb
module SupplierHelper
end

iNeed/app/views/supplier/offers/index.haml
/@Author: Omar Aly
/@Author: Nourhan Aloush
/@Buttons:  1. if the offer is not published, a "Publish Now" button will appear
/           =>  on clicking it, it calls publish in the controller
/           2. if the offer is not activated, and the number of subscribed user > min quantity
/           => on clicking it, calls activate in the controller
/           3. if the offer has expired, extend offer button will apear
/           => on clicking it, it redirects the user to the edit template of the offer
/           4. if the offer is activated, input transaction code link will apear
/           => on clicking it, redirects the user to be able to input the transaction code in another template.
/           5. delete offer is available if the offer is not activated yet, 
/           => on clicking it, deletes the offer and all the transactions relevant to it. 

#flash
  %div{:style => "width:400px"}
    - if flash[:notice]
      .alert.alert-success
        =flash[:notice]
    - if flash[:error]
      .alert.alert-error
        =flash[:error]

-if current_supplier != nil
  -session[:id] = current_supplier.id

-if supplier_signed_in? 
  -if (User.find(session[:id]))._type == 'Supplier'
    %h1 My Offers
    %br
    %br
    %p{style:"font-size:20px;"}
    -if !@Offers.empty?
      = will_paginate @Offers, :container => false
      - @Offers.each do |offer|
        .well
          .row-fluid
            .span6-fluid{:style => "text-align:left"}
              %h2= "Offer Placed On: "
            .span6-fluid{:style => "text-align:left"}
              %h2=link_to offer.need.name, supplier_need_path(offer.need.id.to_s)
              %br
          .row-fluid
            .span2
              =image_tag offer.need.photo.url(:normal),:width =>'80px',:height =>'80px'
            .span6{:style => "text-align:left"}
              %h3= "More information about this offer: "
              %p
                =offer.description
            .span4{:style => "text-align:right"}
              %h3= "Subscribed:" + " #{offer.num_of_subscribed_quantity}/#{offer.quantity}"
              %h3= "Price: " + offer.price.to_s + "$"
              %h3= "Expires on: " + offer.expiry_date.to_s
          .row-fluid
            -if offer.num_of_subscribed_quantity>= offer.min_quantity
              .progress.progress-info.progress-striped.active
                .bar{:style => "width: #{offer.num_of_subscribed_quantity*100/offer.quantity}%;"}
            -else
              .progress.progress-danger.progress-striped.active
                .bar{:style => "width: #{offer.num_of_subscribed_quantity*100/offer.quantity}%;"}
          .row-fluid
            -if offer.activated
              .span12{:style => "text-align:center"}
                =link_to "Input transaction code" , insert_code_supplier_transactions_path(offer.id)
            -else
              -if !offer.expired
                -if offer.published
                  -if offer.num_of_subscribed_quantity>=offer.min_quantity
                    .span6{:style => "text-align:center"}
                      =button_to "Activate Now!" ,  activate_supplier_offers_path(:id => offer.id), :class=>"btn-large  btn-success", :confirm => "Are you sure you want to activate this offer?"
                  -else
                    .span6{:style => "text-align:center"}
                      .alert.alert-error
                        ="Waiting for more subscribers"
                -else
                  .span6{:style => "text-align:center"}
                    =form_tag offer,:method => 'get' do
                      =hidden_field_tag :id,offer.id
                      =submit_tag 'Publish Now!', :class=>"btn-large  btn-success"
	                                  
                .span6{:style => "text-align:center"}
                  =button_to "Delete Offer" , updatedelete_supplier_offers_path(:offer_id => offer.id), :class=>"btn-large  btn-danger" , :confirm => "Are you sure you want to delete this offer?"
              -else
                .span6{:style => "text-align:center"}
                  %h5= "Your offer has expired, Do you want to extend it?"
                  =button_to "Extend Offer" , edit_offer_path(:id => offer.id), method: :get , :class=>"btn-large  btn-success", :confirm => "You will now be redirected to edit your offer and start it again, are you sure you want to proceed?"
                .span6{:style => "text-align:center"}
                  %br
                  =button_to "Delete Offer" , updatedelete_supplier_offers_path(:offer_id => offer.id), :class=>"btn-large  btn-danger", :confirm => "Are you sure you want to delete this offer?"
    -else
      %div{:style => "width:290px"}
        .alert.alert-error
          ="You don't have any offers yet!"
      =button_to "START HERE !!!", needs_path, :method => 'get', :class=>"btn-large  btn-success" 

-else
  = "You are not logged in as a supplier, please try to log in again"