iNeed/config/routes.rb
INeed::Application.routes.draw do

  devise_for :suppliers

  devise_for :admins

  devise_for :customers, :controllers => {:registrations => 'registrations'}

  match '/customer/needs/my_needs' => "customer/needs#my_needs", as: :customer_root
  match '/supplier/offers' => "supplier/offers#index", as: :supplier_root
  match '/admin/suppliers/' => "admin/suppliers#index", as: :admin_root
  root :to => 'home#index'
  match '/auth/:provider/callback' => 'authentications#create'
  match 'admins/searching' => 'admins#searching', :as => :searching
  #match 'transactions/insert_code' => 'transactions#insert_code'
  #match 'transactions/insert_code' => 'transactions#insert_code', :as => :insert_code
  #match 'needs/reporting' => 'needs#reporting'
  #match 'needs/reportneed' => 'needs#reportneed'
  #match "/needs/routing" => "needs#reportingComments"
  #match 'needs/:id/comments/reportingcomment' => 'comments#reportingcomment'
  #match 'comments/reportcomment' => 'comments#reportcomment'
  # match "/needs/routing" => "needs#reporting"
  match 'complaints/admin_index' => 'complaints#admin_index', :as => :admin_index
  match 'complaints/admin_index_redirect' => 'complaints#admin_index_redirect' , :as => :admin_index_redirect
  match 'needs/sorting' => 'needs#sorting'
  match 'customers/customer_profile' => 'customers#customer_profile'
  match 'suppliers/supplier_profile' => 'suppliers#supplier_profile'
  match 'users/change_password' => 'users#change_password'
  #match "/needs/routing" => "needs#reporting"
  match "/my_needs/create" => "my_needs#create"


  resources :authentications
  resources :home
  resources :comments do
    collection do
      get :like
      get :dislike
      get :unlike
    end
  end
  resources :complaints
  resources :transactions
  resources :offers
  resources :admins, :only => [:create, :destroy, :index] do
    collection do
      get :hide_marked_comments
      get :hide_marked_needs
      get :reported
    end
  end
  resources :updates
  resources :suppliers
  resources :customers
  resources :needs do
  resources :comments do
    collection do
      get :reportingcomment
      get :report_comment
    end
  end
  resources :message
  resources :categories
    collection do
      get :search
      get :filter
    end
  end
  resources:relatedneeds
 
  resources :autocomplete ,:only => [] do
    collection do
      get :needs
      get :needs_categories
    end
  end

  resources :categories, :only => [:show]

  namespace :admin do
    resources :categories ,:only => [:index, :create] do
      collection do
        delete :destroy
      end
    end
    resources :home, :only => [:index]
    resources :comments ,:only => [] do
      collection do
        get :reported
        get :warn
        get :ban
        get :delete
      end
    end
    resources :complaints, :only => [:index, :show] do
      collection do
        get :delete
        get :mark_as_read
        get :mark_as_unread
      end
    end
    resources :customers, :only => [:edit] do
      collection do
        get :un_ban_marked_customer
      end
    end
    resources :needs , :only => [] do
      collection do
        get :reported
        get :delete
        get :warn
        get :ban
      end
    end
    resources :suppliers, :only => [:index] do
      collection do
        get :approve
        get :reject
        get :ban
        get :warn
        get :un_ban_marked_supplier
      end
    end
    resources :users , :only => [] do
      collection do
        get :mailto_users
        get :banned
        get :un_ban_marked_user
      end
    end
    resources :questions, :only => [:index, :create]
  end

  namespace :customer do
    resources :comments do
      collection do
        post :reportingcomment
        post :report_comment
      end
    end
    resources :needs do
      collection do
        post :reporting
        post :report_need
        get  :my_needs
        post :un_need
        post :iNeed
        get :like
        get :dislike
        get :unlike
        get :clickme
     end
    end
    resources :feedback, :only => [:new, :create]
    resources :offers do
      collection do
        post :subscribe
        post :unsubscribe
      end
    end  
    resources :categories, :only => [:show]
  end


  namespace :supplier do
    resources :offers, :only => [:index] do
    	collection do
    		post :publish
        post :updatedate
        post :updatedelete
        post :activate
    	end
    end
    resources :complaints do
      collection do
        post :updatedelete
      end
    end
    resources :feedbacks, :only => [] do
      collection do
        post :report
        get :view
      end
    end
    resources :transactions, :only => [:index, :create, :new, :destroy, :show] do
      collection do
        get :insert_code
      end
    end
    resources :categories, :only => [:show] do
      collection do
        get :track
        get :untrack
        post :track
        post :untrack
      end
    end
    resources :needs, :only => [:index, :show] do
      collection do
        post :track
        post :untrack
        get  :hot_needs_supplier
        post :notify_view
        post :notify_action
        post :unnotify
      end
    end
  end



  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :registrations
      resources :keys
      resources :customers
      resources :comments
      resources :offers
      resources :needs do
        collection do
        get :getlistrelatedneeds
        post :report_need
        get :search
        post :iNeed
        post :un_need
        end
      end
     end
   end
end

iNeed/app/controllers/admin/customers_controller.rb
class Admin::CustomersController < AdminsController
#@Author = Mohamed Osama
#@summary = takes the cutomers marked by the admin and loop on them unbanning each one of them
  def un_ban_marked_customer
      $banned_marked_customers = []
      $banned_marked_customers = params[:user_ids]
      for customer_id in $banned_marked_customers
        (Customer.find(customer_id)).update_attribute(:banned, nil)
      end
      redirect_to :action => 'banned'
  end

end

iNeed/app/controllers/admin/needs_controller.rb
#@Author = Dalia William
#@Author = Mohamed Osama
class Admin::NeedsController < AdminController

	#@author = Dalia William
  #@summary = It calls delete_reported_needs in needs controller and passes the needs' ids as parameters. 
  #@paramName: params[:need_ids] => The ids of the needs chosen by the admin in the reported needs view
	def delete
		@needs = params[:need_ids]
		Need.delete_reported_needs(@needs)
		redirect_to :back
	end
  #@author = Mohamed Osama
  #@summary = An action which initializes a list of needs which are reported excluding deleted and hidden needs
  def reported
    @reported_needs = Need.where(reported: true).excludes(deleted: true) - Need.any_in(_id: Admin.find(current_admin.id).hidden_needs)
   end 

  #@author: Dalia William
  #@summary: It first gets the ids of the needs' creators(from the needs ids passed from the view), 
  #          calls warn_customers action (which is in Customer model) than redirects to the reported needs page
  #paramName: params[:reason] => the reason enterred by the admin for warning
  #paramName: params[:need_ids] => the ids of needs selected by the admin
  def warn
		@reason_for_warning = params[:reason]
    @needs = params[:need_ids]
    @customers = @needs.map { |need_id| Need.find(need_id).customer.id  }
    Admin.find(current_admin.id).warn_customers(@customers, @reason_for_warning)
    redirect_to reported_admins_path
  end

  #@Author: Tarek Mehrez
  #@Summary: This action gets the checked needs then gets their creators, then ban_marked_customers 
  #are called on current admin
  #@paramName: :needs_ids -> checked needs by the admin 
  #@paramName: :reason -> reason for banning need creator 
  def ban
    @needs = params[:need_ids]
    @customers = @needs.map { |need_id| Need.find(need_id).customer.id  }
    Admin.find(current_admin.id).ban_marked_customers(@customers,params[:reason],@needs)
    redirect_to reported_admins_path
  end


end

iNeed/app/controllers/api/v1/customers_controller.rb
class Api::V1::CustomersController < Api::V1::BaseController
#@Author: Mohamed Diaa
  #@Summary: All the following are the CRUD actions of the Customer's class
  #          Responding with Json along with the http response status 
  #@ParamName: 

  before_filter :check_banned, :only => [:index, :show, :edit, :update, :destroy, :customer_profile]
  before_filter :is_logged
  before_filter :restrict_access, :except => :create
  
  def check_banned
    unless not_banned?
      respond_with :status => :unprocessable_entity 
    end
  end

  def not_banned?
    if(current_customer)
      !(current_customer.banned)
    end
  end

  def is_logged
    current_customer
  end

  def index
    @customers = Customer.all
    respond_with @customers, :status => :ok
  end

  def show
    @customer = Customer.find(params[:id])
    respond_with @customer 
  end

  def new
    @customer = Customer.new
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def create
    @customer = Customer.new(params[:customer])
      if @customer.save
        respond_with @customer, :status => :created
      else
        respond_with @customer.errors, :status => :unprocessable_entity 
      end
  end

  def update
    @customer = Customer.find(params[:id])
      if @customer.update_attributes(params[:customer])
        respond_with  @customer,  :status => :ok
      else
        respond_with @customer.errors, :status => :unprocessable_entity 
      end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    respond_with head :no_content 
  end


  def customer_profile
    @customer = customer.find(current_customer.id)
  end
end

iNeed/app/controllers/api/v1/needs_controller.rb
#@author: Marina Charles
class Api::V1::NeedsController < Api::V1::BaseController
  respond_to :json
  before_filter :restrict_access, :only => [:iNeed, :un_need, :like, :dislike, :unlike]

  def index
    respond_with Need.all
  end

  def show
    respond_with Need.find(params[:id])
  end
#@author: Marina Charles
#@summary: in this action i put in xml file the information needed to display the similar needs using respond_with
#@need: "id" => gets the need with following id
#@cat_id: gets the category id of that need
#@needcat:"@cat_id" => gets the category of that need
#@listrelatedneeds: places all the similar needs in that list

  def getlistrelatedneeds

    @need = Need.find(params[:id])
    @cat_id = @need.category_id
    @needcat = Category.find(@cat_id) 
    @listrelatedneeds = @needcat.needs
    respond_with @listrelatedneeds

  end
#@author: Marina Charles
#@summary: in report need i put in xml file all the information needed to report a need
#@need: "id" => get the need of the following id
#@report: "report" => i get the content of the report
#@need.report: "report" => i save content in report(string)
#@need.records: "current_customer.id.to_s","@report" => i store the id of customer(key) and the content of report(value) in hash records when clicking on submit(in need's show(view))
#@need.reported: "id" => i set the value to true when the need with this "id" is reported
  def report_need 
    @need = Need.find(params[:id])
    @report = params[:report]
    @need.report = params[:report]
    @need.save
    @need.records.store(current_customer.id.to_s,@report)
    @need.save
    @need.reported = true
    @need.save
   respond_with @need
  end

  def search
    if params[:need_name_auto] != ''
      @needs = Need.tire.search params[:need_name_auto]
      @needs = @needs.map {|n| Need.find(n.id)}
    else
      @needs = []
    end
    respond_with @needs
  end

#@Author: Mohamed Diaa
#@summary: action for needing a certain need
#@ParamName: "params[:id]"" : repewsents the id of the specified need
#@ParamName: "@need": is the need object which was specified in the request
#@ParamName: "@need.total_needers":  is the total number of needer on this specific need "@need"
  def iNeed
    @need = Need.find(params[:id])
    @need.total_needers = @need.total_needers+1
    if @need.save
      @need.customers.concat(current_customer)  
      current_customer.needs.concat(@need)
      #respond_with the @need returns the need after the changes, with http status :OK (201) successful
      respond_with @need, :status => :ok
    else
      #responds_with status Client Error 422 Unprocessable Entity
      respond_with :status => :unprocessable_entity
    end
  end

    #Author :: Sarah El-Sherbiny
    #this is the action for un-need button for the api 
    def un_need
    @need = Need.find(params[:need_id])
    customer_needs = current_customer.needs.length
    @need.total_needers = @need.total_needers-1
    if @need.save
      current_customer.needs.delete(@need)
      @need.customers.delete(current_customer)
    end
    Transaction.remove_transactions_on_need(@need,current_customer)
    respond_with @need
  end

  def sorting
    choice = params["sorting_choice"]
    @needs = Need.tire.search params[:need_name]
    @query = params[:need_name]
    @needs = @needs.map {|n| Need.find(n.id)}
    if choice == 'Ascending'
    @needs = @needs.sort_by { |s| s.name }.to_a
    @needs = @needs.map {|n| Need.find(n.id)}.paginate :page => params[:page],:per_page => 10
    elsif choice == 'Descending'
      @needs = @needs.sort_by { |s| s.name }.to_a
      @needs = @needs.reverse
      @needs = @needs.map {|n| Need.find(n.id)}.paginate :page => params[:page],:per_page => 10
        elsif choice == 'Price_high_to_low'
          @offers = []
          @needs.each do |need|
            @offers << Offer.sorting_offers_desc(need.id)
          end
          @needs = @offers.flatten
          @needs = @needs.map {|n| Need.find(n.id)}.paginate :page => params[:page],:per_page => 10
          elsif 'choice' == 'Price_low_to_high'
            @offers = []
            @needs.each do |need|
              @offers << Offer.sorting_offers_asc(need.id)
            end
            @needs = @offers.flatten
            @needs = @needs.map {|n| Need.find(n.id)}.paginate :page => params[:page],:per_page => 10
            elsif 'choice' == 'Most Recent offers'
              @offers = []
              @needs.each do |need|
                @offers << Offer.sorting_offers_date(need.id)
              end
              @needs = @offers.flatten
              @needs = @needs.map {|n| Need.find(n.id)}.paginate :page => params[:page],:per_page => 10
    end 
    respond_with @needs
  end
  
  #@Author: Nisma El-Nayeb
  #@Summary: api action for liking a comment
  #@ParamName: "comment" => the comment that the current_customer wants to like
  #@ParamName: "current_customer" => the current_customer who likes a comment
  #@ParamName: ":up" => indication that the user is voting up as opposed to voting 
  #            down(dislike)
  def like
    comment = Comment.get_comment(params[:comment])
    current_customer.vote(comment, :up)
    respond_with comment
  end

  #@Author: Nisma El-Nayeb
  #@Summary: api action for disliking a comment
  #@ParamName: "comment" => the comment that the current_customer wants to dislike
  #@ParamName: "current_customer" => the current_customer who dislikes a comment
  #@ParamName: ":down" => indication that the user is voting down as opposed to voting 
  #            up(like)
  def dislike
    comment = Comment.get_comment(params[:comment])
    current_customer.vote(comment, :down)
    respond_with comment
  end

  #@Author: Nisma El-Nayeb
  #@Summary: api action for undoing liking or disliking a comment
  #@ParamName: "comment" => the comment that the current_customer wants to remove his/her
  #            vote from.
  #@ParamName: "current_customer" => the current_customer who wants to remove his/her
  #            vote.
  def unlike
    comment = Comment.get_comment(params[:comment])
    current_customer.unvote(comment)
    respond_with comment
  end
  
end

iNeed/app/controllers/customer/categories_controller.rb
#@Author: Yousra Hazem
class Customer::CategoriesController < CustomerController  
  layout "cust_master"
  def show
    begin
      @category = Category.find(params[:id])
      @cat_name  = @category.name
      @needs = @category.needs.keep_if{|n| !n.deleted}.paginate :page => params[:page],:per_page => 10
    rescue
      flash[:notice] = "Nice try, but next time you have to be smarter! ;D"
      redirect_to my_needs_customer_needs_path
    end
  end

end

iNeed/app/controllers/customer/comments_controller.rb
 #@Author = Doha
 class Customer::CommentsController < ApplicationController



#@Author: "Doha"
#@summary: This action gets the customer ID of a certain comment and saves it as the key of the hash called "recordscomment",
#then it gets the reason why the customer reported this comment and saves it as the value opposite to his ID in the hash,
#and finally it updates the reported boolean to true to indicate that this comment is reported.
#@commentID => gets the comment ID 
#report_type => gets the reason why the customer reported this comment.     
  def report_comment
    @comment = Comment.find(params["comment_id"])
    cust_id = current_customer.id.to_s
    @comment.report_reason = params["report_reason"]
    @comment.update_attributes(reported: true)
    @comment.reported_comments[cust_id]= @comment.report_reason
    @comment.save
    Comment.check_num_reports_on_comment(@comment.id)
    redirect_to :back
  end
end

iNeed/app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

iNeed/app/helpers/admin/needs_helper.rb
module Admin::NeedsHelper
end

iNeed/app/helpers/customer/feedback_helper.rb
module Customer::FeedbackHelper
end

iNeed/app/helpers/customers_helper.rb
module CustomersHelper
end

iNeed/app/helpers/needs_helper.rb
module NeedsHelper

end

iNeed/app/views/customer/needs/_my_needs.html.haml
/Author :: Sarah El-Sherbiny
/@author: Nourhan Azab
/@summary: displays the my_needs list with their subscribed offers. Each need is displayed with an un-need button. My needs are paginated showing 5 needs/page.
-counter=0
-if flash[:notice]
	.alert.alert-success{:style => "width:400px"}
		= flash[:notice] 
%h1 My Needs
%div.span4
	%table.table.table-striped
		-if @my_needs.empty?
			.alert.alert-error
				='You have no needs yet!'
			=link_to "Explore all needs here",needs_path
			
		- @my_needs.each do |need|
			%table.table.table-condensed.table-striped
				%tr
					%td=image_tag need.photo.url(:normal),:width =>'80px',:height =>'80px'
					%td
						%h3= link_to need.name,customer_need_path(need.id.to_s)
					%td=button_to "Un-need" , un_need_customer_needs_path(:need_id => need.id), :class => "btn-large  btn-danger"
				%table.table.table-condensed.table-striped
				%h4 Subscribed Offers
				%div.span4
					-if @my_subscribed_offers[counter].empty?
						%div{:style => "width:290px"}
							.alert.alert-error
								='You have no subscribed offers!'
					-else
						-@my_subscribed_offers[counter].each do |offer|
							%table.table.table-condensed.table-striped
								-if !(offer.deleted)
									%tr
										-need = Need.find(offer.need_id)
										%td
											%b="Need's name:"
											%b="#{offer.need.name}"
									%tr
										%td
											%b="Info: "
											%b="#{offer.description}"	
									%tr	
										%td
											%b="Subscribed: "
											%b="#{offer.num_of_subscribed_quantity} / #{offer.quantity}"
									%tr	
										%td
											%b="Minimum Quantity = #{offer.min_quantity}"	
										%td{color: 'green', align: 'right'}
											%b="Price = #{offer.price}$"
									%tr	 
										%td
											%b="Expires on: #{offer.expiry_date.to_s}"
									%tr
										-if (Transaction.returnTransaction(current_customer.id, offer.id)).pending
											%td
												%b="Status: Pending"
										-else
											%td
												%b="Status: Non-Pending"	
									%tr
										%td
											%b="Progress :"
											.progress.progress-info.progress-striped.active
												.bar{:style => "width: #{offer.num_of_subscribed_quantity*100/offer.quantity}%;"}
									-if (Transaction.returnTransaction(current_customer.id, offer.id)).done
										-if ((Feedback.get_feedback((Transaction.returnTransaction(current_customer.id, offer.id)).id)).nil?)
											%td
												%b="Transaction : Done"
											%td=link_to "Give Feedback" , new_customer_feedback_path(:transaction_id => Transaction.returnTransaction(current_customer.id,offer.id).id),:class =>"btn-small btn-success"
										-else
											%td
												%div{:style => "width:400px"}
													.alert.alert-error
														='This transaction is done but You already gave a feedback'
								%br
				-counter=counter+1
		= will_paginate @my_needs
/display the hot offers and hot needs for customers 		
=render 'hot_stuff'
%script
	$('.pagination a').attr('data-remote', 'true');

iNeed/app/views/customer/needs/_need_form.haml
/@author: Nourhan Azab
/@author: Sarah El-Sherbiny
/@summary: a partial that checkes whether the current logged in customer is a needer or not and accrodingly display a button. If the cutsomer needs this need then un-need button is shown otherwise the need button is shown.
/ to be rendered inside needs show page for iNeed action
-if !@need.is_needer(current_customer)
	=button_to "iNeed", iNeed_customer_needs_path(:id => @need.id, :go_to_my_needsflag => false), :class =>"btn-large btn-primary",:remote => true
-else
	=button_to "Un-need" , un_need_customer_needs_path(:need_id => @need.id), :class=>"btn-large  btn-danger",:remote => true






   

iNeed/app/views/customer/needs/iNeed.js.erb
$("#<%= @need.id %>").html("<%= escape_javascript(render(:partial => "needs/need_widget")) %>");
$("#<%= @need.id %>"+"need_page").html("<%= escape_javascript(render(:partial => "need_form")) %>");
$("#AllComments").html("<%= escape_javascript(render(:partial => "comments/comments_partial")) %>");
$("#offers").html("<%= escape_javascript(render(:partial => "offers")) %>");
$("#desc").html("<%= escape_javascript(render(:partial => "need_info")) %>");

iNeed/app/views/customer/needs/my_needs.html.haml
/Author :: Sarah El-Sherbiny
/@author: Nourhan Azab
/@summary: displays the my_needs list with their subscribed offers. Each need is displayed with an un-need button. My needs are paginated showing 5 needs/page.
-counter=0
-if flash[:notice]
	.alert.alert-success{:style => "width:400px"}
		= flash[:notice] 
%h1 My Needs
%div.span4
	%table.table.table-striped
		-if @my_needs.empty?
			.alert.alert-error
				='You have no needs yet!'
			=link_to "Explore all needs here",needs_path
			
		- @my_needs.each do |need|
			%table.table.table-condensed.table-striped
				%tr
					%td=image_tag need.photo.url(:normal),:width =>'80px',:height =>'80px'
					%td
						%h3= link_to need.name,customer_need_path(need.id.to_s)
					%td=button_to "Un-need" , un_need_customer_needs_path(:need_id => need.id), :class => "btn-large  btn-danger"
				%table.table.table-condensed.table-striped
				%h4 Subscribed Offers
				%div.span4
					-if @my_subscribed_offers[counter].empty?
						%div{:style => "width:290px"}
							.alert.alert-error
								='You have no subscribed offers!'
					-else
						-@my_subscribed_offers[counter].each do |offer|
							%table.table.table-condensed.table-striped
								-if !(offer.deleted)
									%tr
										-need = Need.find(offer.need_id)
										%td
											%b="Need's name:"
											%b="#{offer.need.name}"
									%tr
										%td
											%b="Info: "
											%b="#{offer.description}"	
									%tr	
										%td
											%b="Subscribed: "
											%b="#{offer.num_of_subscribed_quantity} / #{offer.quantity}"
									%tr	
										%td
											%b="Minimum Quantity = #{offer.min_quantity}"	
										%td{color: 'green', align: 'right'}
											%b="Price = #{offer.price}$"
									%tr	 
										%td
											%b="Expires on: #{offer.expiry_date.to_s}"
									%tr
										-if (Transaction.returnTransaction(current_customer.id, offer.id)).pending
											%td
												%b="Status: Pending"
										-else
											%td
												%b="Status: Non-Pending"	
									%tr
										%td
											%b="Progress :"
											.progress.progress-info.progress-striped.active
												.bar{:style => "width: #{offer.num_of_subscribed_quantity*100/offer.quantity}%;"}
									-if (Transaction.returnTransaction(current_customer.id, offer.id)).done
										-if ((Feedback.get_feedback((Transaction.returnTransaction(current_customer.id, offer.id)).id)).nil?)
											%td
												%b="Transaction : Done"
											%td=link_to "Give Feedback" , new_customer_feedback_path(:transaction_id => Transaction.returnTransaction(current_customer.id,offer.id).id),:class =>"btn-small btn-success"
										-else
											%td
												%div{:style => "width:400px"}
													.alert.alert-error
														='This transaction is done but You already gave a feedback'
								%br
				-counter=counter+1
		= will_paginate @my_needs
/display the hot offers and hot needs for customers 		
=render 'hot_stuff'
%script
	$('.pagination a').attr('data-remote', 'true');

iNeed/app/views/customer/needs/my_needs.js.erb
$("#content").html("<%= escape_javascript(render(:partial => "my_needs")) %>");

iNeed/app/views/customer/needs/show.html.haml
/@Author= "Marina Hani Charles"
/@Summary= Their is a table containing the related needs, and the button for report need that is using bootswatch plugin'
/@Author = Nisma el-Nayeb
/@Author = Yousra Hazem
/@Summary = This is the need's page for the customer. A need's details(name, picture, /description.. etc), the offers made on it, the comments made on it and similar needs are /displayed on this page along with buttons for iNeeding the need and reporting the need.
/@Author = Karim Tharwat
/@Summary = there is a form_tag that take the needed parameters for the subscribe method.
- if @need.deleted == true
	%div{:style => "width:280px"}
		.alert.alert-error
			This need has been deleted.

- elsif current_customer != nil
	#container{:style => "width:950px;margin:10px"}

		.div{:style => "height:100px;width:400px;float:right;",:id => "#{@need.id}need_page"}
			- if @banned_customer == false
				= render 'need_form'

		#header{:style => "height:80px;width:800;"}
			%h1= @need.name
			%h2= @need.category.name
			
		#spacereport{:style => "height:50px;width:1000px;float:left;"}
			%br
			- if @banned_customer == false
				- if (@need.records.has_key?(current_customer.id.to_s)) == false && @need.customer_id!= current_customer.id
					%p
						%a.btn{"data-toggle" => "modal", :href => "#myModal", :class =>"btn-small btn-primary"} Report need

					#myModal.modal.hide.fade/
					.modal-header
						%button.close{"data-dismiss" => "modal"} ×
						%h3 Why do you want to report this need?
					.modal-body
						%p 

						=form_tag("report_need", :need_id => @need.id) do
		
							%p
							=radio_button_tag 'report', "Spam", :checked => true
							Spam
							%p
							=radio_button_tag 'report', "Producted corrupted"
							Producted corrupted
							%p
							=radio_button_tag 'report', "Product spoiled" 
							Product spoiled
							=hidden_field_tag :id, params[:id]
							.modal-footer
							
								=submit_tag("Submit",:class => 'btn-primary')
			
		#desc{:style => "height:600px;width:450px;float:left;background:#E8E8E8;overflow:auto;"}
			%p{:style => "margin-left:20px;margin-top:20px;"}
				=image_tag @need.photo.url(:original), :width =>'150px',:height =>'200px'
			%h3{:style => "margin-left:20px;"}
				= "Description: "
			%b{:style => "margin-left:20px;"}
				= @need.description
				/@Author = Yousra Hazem
				/@summary = displays the quantity needed on this need in different locations
				%div{:style => "margin-left:20px; margin-right:20px;"}
					%table.table.table-striped
						%tbody
							- @need.num_of_needers_in_locations.each_key do |location|
								-if @need.num_of_needers_in_locations[location] > 0
									%tr
										%td #{@need.num_of_needers_in_locations[location]} needers in #{location}

				
		#offers{:style => "height:600px;width:400px;float:right;overflow:auto;margin-right:20px;"}
			= render "offers"

		#similarneeds{:style => "float:right;margin-top:20px;margin-right:250px;"}
			%h2= "Similar Needs:"

			%table
				- @listrelatedneeds.each do |need|
					- if need != @need
						%tr
							%td=image_tag (need).photo.url(:normal), :width =>'60px',:height =>'60px'
							%td
								%b= link_to need.name ,customer_need_path(need)

					- if @listrelatedneeds.length == 1
						%td= 'No Similar Needs to be displayed'
						%td
						%td
						%td
						%td= link_to 'New Need', new_need_path


		#comments{:style => "height:600px;width:450px;float:left;overflow:auto;margin-top:20px;"}
			%h3= "Comments"
			%hr{style: "clear: both;"}

			#AllComments
				= render 'comments/comments_partial'
		#space{:style => "height:100px;width:1000;"}
			%br



			


		
		
- elsif current_supplier != nil
	%div{:style => "width:280px"}
		.alert.alert-error
			You are not signed in as a customer.